### ISSUE TITLE
Support directly in the browser

### ISSUE THREAD

**Issue by BHSPitMonkey** [musicope/game#19]
Why require NW rather than support loading the app as a web page in the browser? WebMIDI has been part of Chrome stable since around May, and [will be shipped in Firefox in the future](https://bugzilla.mozilla.org/show_bug.cgi?id=836897).

For example, [here's a demo](http://codepen.io/BHSPitMonkey/pen/xweLpg) that works nicely with my external keyboard.

**Comment by czb** [comment]
Hi,

glad to hear that somebody actually checks the game :).

The problem is with midi file management. As it is now you just add / modify / delete midi file in a folder on your pc and reload the game and it gets updated. I could not find any other solution that would work in browser and could have the same user experience. Even the FileSystem API is hidden from user - i.e. you cannot browse that folder on pc. Then you are left with writing complete system for adding, deleting and modifying midi files and still the user experience would be terrible.

I also used to use Dropbox to store and access midi files and at that time it worked in Google Chrome. But I really did not like that I had to be online and on HTTPS to access the midi files using Dropbox API - to me it is just overkill.

The game could be modified to support both Online Dropbox mode and local NWJS or Electron Atom mode. But at the end of the day, I use the game with my piano almost every day so I do not mind downloading it once :).

BTW: I think I am the only one really using the game so I just developed it to fit my needs and there is still a long list of things I want to fix / add, but playing the piano is just so much better then to work on the game :D

**Comment by abundantmind** [comment]
Hi, I also came across this while looking for an (free) alternative to synthesia.  It's great!  I may fork a copy and develop some better interfaces for some of the settings...fyi.

**Comment by czb** [comment]
@abundantmind  You are more than welcome to do that ;)

**Comment by technomancy** [comment]
Since `electron` segfaults immediately on my machine, I'd be interested in an in-browser version too. Even if the interface for adding .midi files is lame, that's better than no game at all. Is there a way to play in a browser with the most recent release?

**Comment by czb** [comment]
Hi,

take a look at

http://musicope.github.io/?c_songUrl=songs/YOU.mid

https://github.com/musicope/web-game

https://github.com/musicope/musicope.github.io

That is a stripped down demo for web ;) It should work as long as you use the latest google chrome and have piano connected.

Take a look at

https://github.com/musicope/web-game/blob/master/src/typescripts/params.ts

for all the parameters that you can set in the url of the game.

Let me know if you need more assistance

**Comment by technomancy** [comment]
Great; thanks for the tips.

**Comment by czb** [comment]
Let me know if you needed more assistance
